In [1]:
import pandas as pd

In [2]:
#mimiciv_dir = '/data/vision/polina/projects/chestxray/data_mimic_iv/0.4/'
mimiciv_dir = 'data/mimic-iv-1.0/'

In [3]:
diagnoses_icd = pd.read_csv(f'{mimiciv_dir}hosp/diagnoses_icd.csv', low_memory=False)
diagnoses_icd[:10]

   subject_id   hadm_id  seq_num icd_code  icd_version
0    15734973  20475282        3     2825            9
1    15734973  20475282        2    V0251            9
2    15734973  20475282        5     V270            9
3    15734973  20475282        1    64891            9
4    15734973  20475282        4    66481            9
5    11442057  21518990        1    65971            9
6    11442057  21518990        2    64231            9
7    11442057  21518990        6     V270            9
8    11442057  21518990        3    64511            9
9    11442057  21518990        5    65961            9

In [4]:
d_icd_diagnoses = pd.read_csv(f'{mimiciv_dir}hosp/d_icd_diagnoses.csv', low_memory=False)
d_icd_diagnoses[:10]

  icd_code  icd_version                             long_title
0     0010            9         Cholera due to vibrio cholerae
1     0011            9  Cholera due to vibrio cholerae el tor
2     0019            9                   Cholera, unspecified
3     0020            9                          Typhoid fever
4     0021            9                    Paratyphoid fever A
5     0022            9                    Paratyphoid fever B
6     0023            9                    Paratyphoid fever C
7     0029            9         Paratyphoid fever, unspecified
8     0030            9             Salmonella gastroenteritis
9     0031            9                  Salmonella septicemia

In [5]:
drgcodes = pd.read_csv(f'{mimiciv_dir}hosp/drgcodes.csv', low_memory=False)
drgcodes[:10]

,subject_id,hadm_id,drg_type,drg_code,description,drg_severity,drg_mortality
0,15734973,20475282,HCFA,775,VAGINAL DELIVERY W/O COMPLICATING DIAGNOSES,NaN,NaN
1,11442057,21518990,HCFA,765,CESAREAN SECTION W CC/MCC,NaN,NaN
2,10072949,20817034,HCFA,766,CESAREAN SECTION W/O CC/MCC,NaN,NaN
3,13538405,24822466,HCFA,775,VAGINAL DELIVERY W/O COMPLICATING DIAGNOSES,NaN,NaN
4,10287061,27485182,HCFA,775,VAGINAL DELIVERY W/O COMPLICATING DIAGNOSES,NaN,NaN
5,16016170,21252749,HCFA,775,VAGINAL DELIVERY W/O COMPLICATING DIAGNOSES,NaN,NaN
6,14880075,27821335,HCFA,775,VAGINAL DELIVERY W/O COMPLICATING DIAGNOSES,NaN,NaN
7,14678771,28223028,HCFA,766,CESAREAN SECTION W/O CC/MCC,NaN,NaN
8,19952612,23683577,HCFA,775,VAGINAL DELIVERY W/O COMPLICATING DIAGNOSES,NaN,NaN
9,17278669,25247870,HCFA,775,VAGINAL DELIVERY W/O COMPLICATING DIAGNOSES,NaN,NaN

In [6]:
drgcodes[drgcodes['description'].str.contains('hf|heart failure', case=False)]['description'].value_counts()

HEART FAILURE                                                               8972
HEART FAILURE & SHOCK W MCC                                                 3489
HEART FAILURE & SHOCK W CC                                                  3367
PERM CARDIAC PACEMAKER IMPLANT W/O AMI, HEART FAILURE OR SHOCK              1299
HEART FAILURE & SHOCK W/O CC/MCC                                             954
HEART FAILURE & SHOCK W MCC OR PERIPHERAL EXTRACORPOREAL MEMBRANE OXYGEN     622
PERMANENT CARDIAC PACEMAKER IMPLANT W AMI, HEART FAILURE OR SHOCK            102
CARDIAC DEFIB IMPLANT W CARDIAC CATH W/O AMI/HF/SHOCK W MCC                   75
CARDIAC DEFIB IMPLANT W CARDIAC CATH W AMI/HF/SHOCK W MCC                     44
CARDIAC DEFIB IMPLANT W CARDIAC CATH W/O AMI/HF/SHOCK W/O MCC                 41
CARDIAC DEFIB IMPLANT W CARDIAC CATH W AMI/HF/SHOCK W/O MCC                   14
Name: description, dtype: int64

In [7]:
# merge tables
df_ids_icds = pd.merge(diagnoses_icd, d_icd_diagnoses, on = ['icd_code','icd_version'], how='left')
df_merged = pd.merge(df_ids_icds, drgcodes, on = ['hadm_id', 'subject_id'], how='left')
df_merged = df_merged.drop(columns=['drg_severity', 'drg_mortality'])
df_merged[:10]

,subject_id,hadm_id,seq_num,icd_code,icd_version,long_title,drg_type,drg_code,description
0,15734973,20475282,3,2825,9,Sickle-cell trait,HCFA,775.0,VAGINAL DELIVERY W/O COMPLICATING DIAGNOSES
1,15734973,20475282,3,2825,9,Sickle-cell trait,APR,560.0,VAGINAL DELIVERY
2,15734973,20475282,2,V0251,9,Carrier or suspected carrier of group B strept...,HCFA,775.0,VAGINAL DELIVERY W/O COMPLICATING DIAGNOSES
3,15734973,20475282,2,V0251,9,Carrier or suspected carrier of group B strept...,APR,560.0,VAGINAL DELIVERY
4,15734973,20475282,5,V270,9,"Outcome of delivery, single liveborn",HCFA,775.0,VAGINAL DELIVERY W/O COMPLICATING DIAGNOSES
5,15734973,20475282,5,V270,9,"Outcome of delivery, single liveborn",APR,560.0,VAGINAL DELIVERY
6,15734973,20475282,1,64891,9,Other current conditions classifiable elsewher...,HCFA,775.0,VAGINAL DELIVERY W/O COMPLICATING DIAGNOSES
7,15734973,20475282,1,64891,9,Other current conditions classifiable elsewher...,APR,560.0,VAGINAL DELIVERY
8,15734973,20475282,4,66481,9,"Other specified trauma to perineum and vulva, ...",HCFA,775.0,VAGINAL DELIVERY W/O COMPLICATING DIAGNOSES
9,15734973,20475282,4,66481,9,"Other specified trauma to perineum and vulva, ...",APR,560.0,VAGINAL DELIVERY

In [8]:
# drop any rows that don't have a drg_code
df_merged = df_merged.dropna(subset=['drg_code'], how='any')

In [9]:
# select rows where DRG code contains "hf" or "heart failure"
df_sub = df_merged[df_merged['description'].str.contains('hf|heart failure', case=False)]
# there are some drg codes that specify "w/o hf" or "w/o heart failure" - don't include those rows
df_sub = df_sub[~df_sub['description'].str.contains('W/O AMI/HF/SHOCK|W/O AMI, HEART FAILURE OR SHOCK', case=False)]
df_sub

,subject_id,hadm_id,seq_num,icd_code,icd_version,long_title,drg_type,drg_code,description
5635,19545081,27086801,16,32723,9,Obstructive sleep apnea (adult)(pediatric),HCFA,291.0,HEART FAILURE & SHOCK W MCC
5636,19545081,27086801,16,32723,9,Obstructive sleep apnea (adult)(pediatric),APR,194.0,HEART FAILURE
5637,19545081,27086801,17,04111,9,Methicillin susceptible Staphylococcus aureus ...,HCFA,291.0,HEART FAILURE & SHOCK W MCC
5638,19545081,27086801,17,04111,9,Methicillin susceptible Staphylococcus aureus ...,APR,194.0,HEART FAILURE
5639,19545081,27086801,9,42833,9,Acute on chronic diastolic heart failure,HCFA,291.0,HEART FAILURE & SHOCK W MCC
...,...,...,...,...,...,...,...,...,...
9434111,16799562,23401334,6,M341,10,CR(E)ST syndrome,APR,194.0,HEART FAILURE
9434112,16799562,23401334,9,E039,10,"Hypothyroidism, unspecified",HCFA,292.0,HEART FAILURE & SHOCK W CC
9434113,16799562,23401334,9,E039,10,"Hypothyroidism, unspecified",APR,194.0,HEART FAILURE
9434114,16799562,23401334,10,D638,10,Anemia in other chronic diseases classified el...,HCFA,292.0,HEART FAILURE & SHOCK W CC
9434115,16799562,23401334,10,D638,10,Anemia in other chronic diseases classified el...,APR,194.0,HEART FAILURE

In [10]:
# remove the hadm_ids that have a long title with heart failure in them, since the ICD codes already account for them
no_hf_icd = []
for hadm_id in df_sub.hadm_id.unique():
    df_hadm_id = df_sub[df_sub['hadm_id'] == hadm_id]
    if len(df_hadm_id[df_hadm_id['long_title'].str.contains('heart failure', case=False)]) == 0:
        no_hf_icd.append(hadm_id)
df_no_hf_icd = df_sub[df_sub['hadm_id'].isin(no_hf_icd)]
df_no_hf_icd[:10]

,subject_id,hadm_id,seq_num,icd_code,icd_version,long_title,drg_type,drg_code,description
531476,18109438,25078243,1,41071,9,"Subendocardial infarction, initial episode of ...",APR,170.0,"PERMANENT CARDIAC PACEMAKER IMPLANT W AMI, HEA..."
531478,18109438,25078243,13,V1254,9,Personal history of transient ischemic attack ...,APR,170.0,"PERMANENT CARDIAC PACEMAKER IMPLANT W AMI, HEA..."
531480,18109438,25078243,11,29410,9,Dementia in conditions classified elsewhere wi...,APR,170.0,"PERMANENT CARDIAC PACEMAKER IMPLANT W AMI, HEA..."
531482,18109438,25078243,8,2449,9,Unspecified acquired hypothyroidism,APR,170.0,"PERMANENT CARDIAC PACEMAKER IMPLANT W AMI, HEA..."
531484,18109438,25078243,14,V5861,9,Long-term (current) use of anticoagulants,APR,170.0,"PERMANENT CARDIAC PACEMAKER IMPLANT W AMI, HEA..."
531486,18109438,25078243,2,82021,9,Closed fracture of intertrochanteric section o...,APR,170.0,"PERMANENT CARDIAC PACEMAKER IMPLANT W AMI, HEA..."
531488,18109438,25078243,5,42731,9,Atrial fibrillation,APR,170.0,"PERMANENT CARDIAC PACEMAKER IMPLANT W AMI, HEA..."
531490,18109438,25078243,4,42613,9,Other second degree atrioventricular block,APR,170.0,"PERMANENT CARDIAC PACEMAKER IMPLANT W AMI, HEA..."
531492,18109438,25078243,12,311,9,"Depressive disorder, not elsewhere classified",APR,170.0,"PERMANENT CARDIAC PACEMAKER IMPLANT W AMI, HEA..."
531494,18109438,25078243,3,81504,9,Closed fracture of neck of metacarpal bone(s),APR,170.0,"PERMANENT CARDIAC PACEMAKER IMPLANT W AMI, HEA..."

In [11]:
# only keep rows where ICD codes include:
#" cardiogenic shock", "left ventricular failure, unspecified", "shock, unspecified", or pleural effusion or fluid overload
df_no_hf_icd = df_no_hf_icd[df_no_hf_icd['long_title'].str.contains('cardiogenic shock|left ventricular failure, unspecified|shock, unspecified|Pleural effusion, not elsewhere classified|Fluid overload, unspecified', case=False)]
df_no_hf_icd_hadm = df_no_hf_icd[['subject_id','hadm_id','long_title', 'icd_code','icd_version', 'description']].drop_duplicates(subset=['hadm_id'])
print(len(df_no_hf_icd))
print(len(df_no_hf_icd_hadm))
# df_no_hf_icd
df_no_hf_icd_hadm

21
19

,subject_id,hadm_id,long_title,icd_code,icd_version,description
996683,19897344,23853450,Cardiogenic shock,78551,9,HEART FAILURE & SHOCK W MCC
1667429,14014101,25893056,Cardiogenic shock,78551,9,HEART FAILURE & SHOCK W MCC
2022992,18106399,26894755,"Shock, unspecified",78550,9,HEART FAILURE & SHOCK W MCC
2345641,11459188,24637585,"Shock, unspecified",78550,9,HEART FAILURE & SHOCK W MCC
2641048,16030932,23928900,Cardiogenic shock,78551,9,HEART FAILURE & SHOCK W MCC
3310907,17716210,25507754,"Shock, unspecified",78550,9,HEART FAILURE & SHOCK W CC
3998205,19209492,24937094,Cardiogenic shock,78551,9,CARDIAC DEFIB IMPLANT W CARDIAC CATH W AMI/HF/...
4626230,11708108,20935519,Cardiogenic shock,78551,9,CARDIAC DEFIB IMPLANT W CARDIAC CATH W AMI/HF/...
5866161,15049237,28367823,"Left ventricular failure, unspecified",I501,10,HEART FAILURE & SHOCK W MCC
5964170,14461781,29743557,"Pleural effusion, not elsewhere classified",J90,10,HEART FAILURE & SHOCK W CC
6009347,10023117,21133938,Cardiogenic shock,R570,10,HEART FAILURE & SHOCK W MCC
6200791,11015070,23323677,Cardiogenic shock,R570,10,HEART FAILURE & SHOCK W CC
6258376,19272859,29450359,"Shock, unspecified",R579,10,HEART FAILURE & SHOCK W MCC
6364156,17158198,28342166,"Shock, unspecified",R579,10,HEART FAILURE & SHOCK W MCC
6961185,16533299,25815566,"Shock, unspecified",R579,10,HEART FAILURE & SHOCK W CC
7085083,19022591,23484523,"Pleural effusion, not elsewhere classified",J90,10,HEART FAILURE & SHOCK W MCC
7394001,12008505,22031009,"Fluid overload, unspecified",E8770,10,HEART FAILURE & SHOCK W CC
8017930,15295867,28482356,"Shock, unspecified",R579,10,HEART FAILURE & SHOCK W MCC
8418193,14903722,23470534,"Shock, unspecified",R579,10,HEART FAILURE & SHOCK W CC