In [22]:
from PIL import Image
import pandas as pd
import numpy as np
from dateutil import parser

In [4]:
adm_with_cxr = pd.read_csv('final_cohort_with_mimicids.csv')
adm_with_cxr.head()

,Unnamed: 0,Unnamed: 0.1,subject_id,hadm_id,admittime,dischtime,deathtime,edregtime,edouttime,chronic_dialysis,...,30d_hf,er_hf,48h,14d,30d,er,last_study_id,last_dicom_id,last_study_time,mimic_id
0,7,7,10003400,20214994,2137-02-24 10:00:00,2137-03-19 15:45:00,0,0,0,False,...,0,0,0,0,0,0,52437868,2f6a5fc9-40af95f8-d8762332-f56005ea-b5f85cc2,2137-03-09 20:29:58.453000,p10003400_s52437868_2f6a5fc9-40af95f8-d8762332...
1,8,8,10003502,29011269,2169-08-26 16:14:00,2169-08-28 15:20:00,0,2169-08-26 12:31:00,2169-08-26 22:11:00,False,...,0,0,0,0,0,0,50084553,70d7e600-373c1311-929f5ff9-23ee3621-ff551ff9,2169-08-27 08:16:56.250000,p10003502_s50084553_70d7e600-373c1311-929f5ff9...
2,16,16,10011938,22624746,2128-01-02 21:04:00,2128-01-11 16:01:00,0,0,0,False,...,0,1,0,0,0,1,56362279,c6eed867-d6efb38a-438501f9-9d2506e9-a0c958f8,2128-01-03 09:36:34,p10011938_s56362279_c6eed867-d6efb38a-438501f9...
3,17,17,10011938,23501236,2128-02-11 16:11:00,2128-02-26 16:29:00,0,2128-02-11 12:35:00,2128-02-11 17:34:00,False,...,0,0,0,0,0,1,51895247,bf724128-9131f33a-6fd065d5-19041750-9e7f8707,2128-02-16 09:07:57.093000,p10011938_s51895247_bf724128-9131f33a-6fd065d5...
4,18,18,10012853,26369609,2175-04-05 15:36:00,2175-04-10 16:55:00,0,2175-04-05 06:22:00,2175-04-05 17:10:00,False,...,0,0,0,0,0,1,58181999,aac02704-c647b84c-58d5df12-c9857852-e1536bba,2175-04-07 13:18:41.031000,p10012853_s58181999_aac02704-c647b84c-58d5df12...

In [7]:
for i in range(len(adm_with_cxr)):
    jpg_path = f"p{str(adm_with_cxr['subject_id'].iloc[i])[0:2]}/p{str(adm_with_cxr['subject_id'].iloc[i])}/s{str(adm_with_cxr['last_study_id'].iloc[i])}/{str(adm_with_cxr['last_dicom_id'].iloc[i])}.jpg"
    jpg_path
    png_path = f"images/{str(adm_with_cxr['mimic_id'].iloc[i])}.png"
    png_path
    im1 = Image.open(jpg_path)
    im1 = im1.resize((256,256))
    im1.save(png_path)